FEMessage/el-data-table

README.md, src/el-data-table.vue
fix text-transform mistake && add blank before `element-ui`
=> Update README.md && fix invalid operationColumns

src/el-data-table.vue
🤭 emit ‘onDialogClose’ when dialogVisible is false, so u can do some operation when dialog is going to close
=> 😐emit new/edit event

src/el-data-table.vue
增加onNew&onEdit方法
适用于想使用el-data-table默认的新编、编辑按钮，但需要自定义点击行为的情况
=> 增加onNew&onEdit

stories/expand.vue, stories/index.js
=> 增加expand的用例

.storybook/config.js, package.json, src/el-data-table.vue
- 替换原有的el-form-renderer为@femessage/el-form-renderer
- 替换updateValue为updateForm
- 添加 dialog 打开触发 dialog-open 事件
=> Adaptation renderer

src/el-data-table.vue
- 修复 updateForm 的错误调用
- remove hack for bug: https://github.com/ElemeFE/element/issues/8615
=> fix update value

README.md
=> 新增formatter文档说明

src/el-data-table.vue
For: #41 
⚡️⚡️⚡️⚡️⚡️
**_另推荐 #57_**
=> fix: 使用 button.loading 代替 v-loading

package.json
package.json
to solve yarn build error in ci
this pr use netlify to test
=> move-peerDepends-to-devDependens

src/el-data-table.vue
为了美观
vetur插件设置template部分formater为prettyhtml，然后格式化
=> style: 对el-data-table.vue进行格式化

.babelrc, .travis.yml, LICENSE, build.sh, notify.sh, package.json, test/index.test.js, yarn.lock
build & deploy & notify without human
Update cli that support auto notify
=> ci: build & deploy & notify without human

.travis.yml, build.sh
fix notify with no msg body bug
just sleep 3s before notify😂
=> ci: optimize release process

docs/has-pagination=false.md, docs/no-pagination.md, src/el-data-table.vue
现在有不分页查询全部数据的需求，resolve #83 
- noPaginationSize标记为deprecated
- 判断当hasPagination===false时，接口传参page=-1
=> feat: 不分页时，接口传参page=-1

src/el-data-table.vue
=> feat: 删除弹窗的确认按钮用danger样式

src/el-data-table.vue
=> fix: 出现多个computed

src/el-data-table.vue
=> docs: 公开getList方法

README-en.md, README.md, docs/basic.md, docs/before-confirm.md, docs/before-search.md, docs/can-search-collapse.md, docs/extra-body.md, docs/extra-query.sync.md, docs/faq.md, docs/first-page.md, docs/has-pagination=false.md, docs/is-tree.md, docs/on-new-edit-delete.md, docs/router-mode=history.md, docs/save-query.md, docs/slot-search.md, package.json, yarn.lock
这是一个绝对值得的更新,[点击查看release](https://github.com/FEMessage/el-form-renderer/releases/tag/v1.6.0)
```console
$ jest
PASS  test/query.test.js
测试 stringify
✓ 基本功能 (4ms)
✓ 自定义 equal & delimiter (1ms)
测试 parse
✓ 基本功能 (2ms)
✓ 自定义 equal & delimiter
测试 set
✓ 通过所有用例 (3ms)
✓ 多次set仍是幂等操作 (2ms)
✓ url已经有query时会被替换成新的 (2ms)
测试 get
✓ 通过所有用例 (3ms)
测试 clear
✓ 通过所有用例 (2ms)
Test Suites: 1 passed, 1 total
Tests:       9 passed, 9 total
Snapshots:   0 total
Time:        2.835s
Ran all test suites.
```
=> feat(deps): upgrade `@femessage/el-form-renderer` to `1.6.0`

.babelrc.js, .github/badge.yml, .grenrc.js, package.json
```console
$ jest
PASS  test/query.test.js
PASS  test/select-strategy.test.js
Test Suites: 2 passed, 2 total
Tests:       16 passed, 16 total
Snapshots:   0 total
Time:        6.642s
Ran all test suites.
```
=> chore: use vue-sfc-cli upgrade

docs/faq.md
=> docs(faq): 记录通过v-if切换el-data-table时出现无法重置searchForm的问题

README-en.md, README.md, package.json
=> chore: scope package name

.babelrc.js, .stylelintrc, notify.sh, package.json, styleguide.config.js, yarn.lock
组件框架需要更新以使用框架新的特性
- 框架自带更新，版本`1.10.4`
- `yarn test` 正常
- `precommit` 正常
=> chore: 更新 cli 配置

docs/slot-search.md
- httpStatusCode got 422 when fetch github api 
- set a default query for github api
=> fix: error 422 when fetch github api without query 「q」

src/el-data-table.vue
- 部分允许通过 $refs 访问的组件实例方法没有在文档中体现
- api 文档补充 resetSearch 方法
=> docs: expose resetSearch as public method in api document

src/el-data-table.vue
fix #186 
getList时会往history推很多状态，导致回退很多次才能到上一页面
getList使用replaceState
=> fix: 保存查询参数时使用 replaceState

README-en.md, README.md, build/rollup.config.js, package.json, src/components/the-dialog.vue, src/el-data-table.vue, src/index.js, styleguide.config.js, yarn.lock
减少下次commit时携带的format更改
1. stylus => less
2. 项目根目录执行`npx prettier --write "**/*.@(js|vue|md|json)"`
[x] yarn test
[x] preview
=> chore: 执行prettier & stylus => less

docs/extra-query.sync.md
相关的 issue #195 
正确使用方法可参考 https://github.com/FEMessage/el-data-table/pull/196#issuecomment-519836370
为了避免重复出现, 需要把文档完善一下.
```diff
- rate: 2,
+ rate: null,
```
=> docs: `extraQuery`的正确使用方法

src/el-data-table.vue
=> refactor: 删除逻辑使用async/await精简代码

docs/slot-form.md, src/components/the-dialog.vue, src/el-data-table.vue
fix #202 
有些用户想结合form-renderer的方便和slot的自由度
给slot-form传递formData
https://deploy-preview-212--el-data-table.netlify.com/#/Demo/slot-form
点击新增、修改按钮，功能正常
=> feat: slot-form增加作用域数据

docs/faq.md
close #224
补充说明 el-form 包裹 el-data-table 需要注意 form element 的默认 submit 事件
=> docs(faq.md): 增加禁用 submit 默认行为说明

docs/basic.md, docs/before-search.md, docs/clear-selection.md, docs/expand.md, docs/extra-body.md, docs/extra-buttons.md, docs/first-page.md, docs/has-pagination=false.md, docs/id.md, docs/is-tree.md, docs/new-text.md, docs/on-new-edit-delete.md, docs/persist-selection.md, docs/save-query.md, docs/search-item-collapsible.md, docs/slot-form.md, docs/slot-header.md, docs/slot-no-data.md
=> docs: 更新mock接口

README-zh.md, README.md, docs/faq.md
=> docs: 更换图床

docs/formatter.md, styleguide.config.js
=> docs(formatter): 增加 formatter 使用 jsx 的演示

docs/formatter.md
=> docs: 让文档在 CI 环境下不报错

docs/search-immediately.md, src/el-data-table.md
=> docs: 补充 searchImmediately 文档

docs/axios-config.md, src/el-data-table.vue
有需求是要给请求加上特殊headers，不同接口不同headers，所以无法在全局axios进行配置，需要在特定的请求里进行配置
通过props取得父组件传进来的extraConfig属性，给axios请求加上config参数
=> feat: 支持配置axios的config

docs/on-success.md, src/el-data-table.vue
fix #268 
打开新的 onSuccess 示例，执行新增、编辑、删除操作，可看到以下提示
=> feat: 新增 onSuccess 钩子

docs/can-search-collapse.md, src/el-data-table.vue
CLOSE #277 
顺便增加一个插槽
调整一下 dom 位置
Before
After
=> fix: slot header 应该在折叠按钮前面

docs/persist-selection.md, src/el-data-table.vue, src/utils/select-strategy.js
CLOSE #278 
如果有 selectable 传入，则需要先过滤一遍
Before
After
=> fix: select all 应该过滤掉 selectable 为 false 的行

src/el-data-table.vue
https://github.com/FEMessage/el-data-table/pull/274
漏网之鱼，我看漏了。
=> fix: 没 searchForm 时仍有搜索🔍按钮

docs/before-search.md, src/el-data-table.vue
=> fix: beforeSearch增加表单数据参数

src/el-data-table.vue, yarn.lock
fix #295 
根据返回的 total 算出最后一页，然后重新发起请求
=> fix: 超出页码的请求自动跳回最后一页

src/components/text-button.vue
=> fix: 修复 extraButtons 未正确显示 disabled 状态的问题

src/el-data-table.vue
`#` 乃至所有参数应当被转义才能附在 url 上
用 axios 的 params 配置
basic 示例，输入 #，点击查询
=> fix: 搜索参数出现 # 时丢失

src/el-data-table.vue
处理搜索表单样式问题
Describe your steps:
1. 新增类名
=> fix: 给 el-form-renderer 容器增加类名

package.json, src/el-data-table.vue
=> chore:  dialogForm 让 api 命名更符合直觉
