FEMessage/el-data-table

src/el-data-table.vue

fix #30 
修复由于使用默认的dataPath导致的自定义dataPath无效

fix #30 不分页时，设置dataPath 无效

---

src/self-loading-button.vue

- fix: rendere error because the useless components property

fix(self-loading-button): remove warning of property <type>

---

src/el-data-table.vue

Why is this change required? What problem does it solve?
fix #66 
原因 https://github.com/ElemeFE/element/pull/5920#issuecomment-329700599
初始`searchForm`长度为`0`或者没有设置: 动态设置表单会触发表单提交行为
Describe your changes in detail
为表单组件设置 `<el-form-renderer @submit.native.prevent/>`
删除 `searchForm.$el.setAttribute('action', 'javascript:;')`
Show your xmind or other mind map

fix: 修复搜索表单提交行为

---

src/self-loading-button.vue

fix #76
导致触发表单提交,"刷新"页面
处理渲染的 `button.type`

fix: 处理`self-loading-button`触发表单提交行为

---

src/el-data-table.vue

按钮样式新规范，参考ant-design
1. type改成text
2. 删除按钮颜色直接使用ui规范写死。
- 因为没有合适的element class组合同时解决平时+hover状态的danger颜色
- 2.8以后的element提供link组件完美解决这个问题

feat: 操作列按钮改成文字按钮

---

src/el-data-table.vue
src/text-danger-button.vue

删除按钮写死style，日后无法随自定义主题的element变化
1. 直接在el-button上写class，无法处理hover的情况
2. 利用color: inherit，在el-button之上包裹📦一层div，就可以解决hover和优先级问题

feat: 删除按钮颜色使用class替代style

---

README.md

1. 目录排除一级标题和目录本身
2. 章节标题统一大写开头

docs: README目录规范化

---

src/el-data-table.vue

同一事件`vue-styleguide`只能识别最后一次`$emit`的注释
```js
/**
* 你以为这句话会进入文档
*/
this.$emit('event')
this.$emit('event') // 最后一次$emit没注释，结果就是没文档
```

docs: 补充event的文档

---

docs/save-query.md
src/el-data-table.vue

当页面中有多个table时，query参数会互相影响
通过saveQuery属性开关query的功能。一般来说页面中只有一个table可以开启saveQuery
https://deploy-preview-139--el-data-table.netlify.com/#!/save-query/1

feat: 增加属性saveQuery控制开启query保存功能

---

src/el-data-table.vue
src/self-loading-button.vue

fix: self-loading-button在header处应该是el-button样式

---

.gitignore
docs/slot-no-data.md
src/el-data-table.vue

当从url首次请求到数据为空时，显示自定义内容为空的内容
例如：获取内容为空时：显示自定义内容不显示table，search form，page.
无查询条件获取内容非空时：正常显示
非首次查询条件为空时：正常显示
1. 第一次查询时
1. 获取数据total字段为0，显示slot内容，不显示其余内容。
2. 获取数据total字段不为0，不显示slot内容，显示原有内容。
2. 非首次查询时，获取数据total字段为0，不显示slot内容，显示原有内容。
docs/slot-no-data.md

feat: 增加no-data slot

---

README.md

新浪图床在serverless-console显示403
将README拷贝到语雀发布再导出Markdown，将图片链接拷贝回来
将语雀cdn的图片地址放到serverless-console，图片正常显示
无

docs: README弃用新浪图床使用语雀cdn

---

docs/slot-header.md
src/el-data-table.vue

resolve #175 , close #103
在header末尾增加作用域插槽slot=header，传入selected
打开preview中[slot-header章节](https://deploy-preview-177--el-data-table.netlify.com/#!/slot-header/1)，查看效果
1. api文档增加slot=header介绍
2. demo中增加slot-header案例

feat: 增加header-slot

---

src/el-data-table.vue

原 showRow 方法想要给显示的行(tr)加一个淡入的动画，但是由于没有用 ";" 分隔，导致没加上，tr 也就没有淡入效果
1. 用 row-class-name 代替 row-style
2. 用添加相应类名的方式代替内联样式
1. 能够正确给行加上淡入动画，显示时能有淡入效果
2. 对于 isTree 类型，能够正确控制行的显示与隐藏
- Before
- After
无需文档修改

fix: 修复 tr 淡入动画没添加上

---

src/el-data-table.vue

fix #182 
header的判定条件不完备导致的
抽离hasHeader逻辑，且`hasSelect && hasDelete`时才构成header存在的充分条件（非必要）
设置`hasNew: false`

fix: header 在没有头部按钮时出现 22px 高度的问题

---

src/components/the-dialog.vue
src/el-data-table.vue

#200 之前提出的增加 el-dialog 的width，close-on-click-modal等属性的设置
Describe your steps:
增加dialogAttrs属性
You may use xmind or other mind map to show you logic
Show your test case
you'd better show `before` and `after` 
https://element.eleme.cn/#/zh-CN/component/dialog#attributes
```
dialogAttrs: {
width: "80%",
closeOnClickModal: false
},
```

feat: 支持设置对话框属性 dialogAttrs

---

docs/search-collapse-always-display.md
docs/search-item-collapsible.md
src/components/search-form.vue
src/el-data-table.vue
yarn.lock

用户需求(当搜索项多并且部分重要的时候)
当某表单项设置为不可折叠时,折叠与否总是可见.
```js
const content = [
{
collapsible: false
}
]
```
- 封装一个组件,他包含 2 个表单(1个是全部表单项 **{A}** ,另1个是只显示[总是可见]的表单项 **{B}** )
- 获取状态: `isSearchCollapse` ,开启折叠状态 `canSearchCollapse` 和表单项配置: `searchForm` 
- 如果没开启 canSearchCollapse 则不渲染(v-if) **B** 表单, 则保持原始行为
- return
- 赋值给表单
- 默认表单项赋值给 **A** 表单
- 筛选出[总是可见]的表单项赋值给 **B** 表单
- 根据 isSearchCollapse 切换实际显示的表单
- 根据 isSearchCollapse 的变动,来回赋值表单值, A->B, A<-B
- 因为折叠后与否,用户都有可能变更表单输入的值, 确保他们的输入一致.
```console
$ jest --verbose
PASS  test/query.test.js
测试 stringify
✓ 基本功能 (9ms)
✓ 自定义 equal & delimiter (1ms)
测试 parse
✓ 基本功能 (3ms)
✓ 自定义 equal & delimiter (1ms)
测试 set
✓ 通过所有用例 (10ms)
✓ 多次set仍是幂等操作 (3ms)
✓ url已经有query时会被替换成新的 (4ms)
测试 get
✓ 通过所有用例 (3ms)
测试 clear
✓ 通过所有用例 (2ms)
PASS  test/select-strategy.test.js
测试 normal …
```

feat: searchForm 内容支持属性 collapsible=false，在搜索区域折叠后仍可见

---

src/el-data-table.vue

close #210
点击查看或编辑或新增按钮时，如果用户是把 hasDialog 设置为 false，将会报错
1. 删除 hasDialog prop
2. 改用 computed 判断是否渲染弹窗
文档中 hasDialog 参数被删除

fix: 使用需要弹窗的功能并把 hasDialog 设置为 false 时, 将会报错

---

src/el-data-table.vue

re #214 
移除 `hasDialog` 相关的代码
```console
$ jest --verbose
PASS  test/query.test.js
测试 stringify
✓ 基本功能 (9ms)
✓ 自定义 equal & delimiter (1ms)
测试 parse
✓ 基本功能 (2ms)
✓ 自定义 equal & delimiter (7ms)
测试 set
✓ 通过所有用例 (5ms)
✓ 多次set仍是幂等操作 (3ms)
✓ url已经有query时会被替换成新的 (2ms)
测试 get
✓ 通过所有用例 (3ms)
测试 clear
✓ 通过所有用例 (2ms)
PASS  test/select-strategy.test.js
测试 normal 模式
✓ onSelectionChange (7ms)
✓ toggleRowSelection (2ms)
✓ clearSelection (1ms)
测试 persistSelection 模式
✓ onSelect (3ms)
✓ onSelectAll (1ms)
✓ toggleRowSelection (2ms)
✓ clearSelection
Test Suites: 2 passed, 2 total
Tests:       16 passed, 16 total
Snapshots:   0 total
Time:        6.335s
Ran all test suites.
```

refactor: remove hasDialog related code

---

docs/slot-search.md
src/components/search-form.vue
src/el-data-table.vue
src/utils/extract-keys.js
test/extract-keys.test.js

用户需求
```html
<el-data-table>
<el-form-item slot="search:gender" label="Oh My Slot">
<el-input value="slot=search:gender" />
</el-form-item>
</el-data-table>
```
```console
$ jest --verbose test/extract-keys.test.js
PASS  test/extract-keys.test.js
✓ 提取指定 key `search:` (5ms)
✓ 提取符合全部 key `search` (1ms)
✓ 提取不存在的 key
Test Suites: 1 passed, 1 total
Tests:       3 passed, 3 total
Snapshots:   0 total
Time:        3.109s
```
- `slot-search.md` 添加一个定位插槽的输入框 `slot=search:q`
```diff
<template>
<el-data-table v-bind="$data">
<template slot="search">
<el-tag>slot=search</el-tag>
<el-rate v-model="extraQuery.rate" style="display: inline-block"></el-rate>
</template>
+   <template slot="search:q">
+     <el-form-item>
+       <el-tag slot="label">slot=search:q</el-tag>
+       <el-input></el-input>
+ …
```

feat: 搜索表单支持定位插槽

---

src/el-data-table.vue

- 项目需求, 期望统一所有按钮风格!
1. 提供 `prop: operationButtonType`
1. 默认保持为 `text` 风格, 可切换至 `button` 风格
1. 利用 `self-loading-button` 本身已有的 `prop: isText` 来切换按钮风格
1. 去掉主文件注册的 `text-button` 组件
1. 其余保持默认

feat: 支持切换操作栏按钮风格

---

docs/guide-contributing-correctly.md
src/components/the-dialog.vue
src/el-data-table.vue

close #216
- 用户需求: 为了让表格按钮跟项目统一对齐,与整体风格保持一致.
1. 提供 `prop.buttonSize`
2. 应用于所有组件本身自带的 button, 包括搜索区域,头部按钮区域,对话框区域和操作栏按钮(文本按钮不会影响)
3. 保持默认为 `small`, 其余选项跟 el-button.size 保持一致
- docs/guide-contributing-correctly.md

feat: 支持统一定制按钮大小

---

src/el-data-table.md
src/el-data-table.vue
src/index.js
src/utils/search-immediately-item.js

- 项目需求, 项目列表庞大的时候, 自动搜索会省心一点点.
- 既然无法保证 component 实际上是什么, 各种 type 与 component 来回牵扯情况, 使用一种最保证的方法去实现, 即使需要多写点代码.
- type: 'input' <=> component: 实际上是 'input'
- type: 'select' <=> component: 实际上是 'select'
- ...
1. 提前处理一遍 searchForm 配置
2. 当 这个表单项 存在 `searchImmediately: true` 的时候, 值表更时触发搜索行为.
```diff
{
type: 'select',
id: 'select',
label: 'select',
+ searchImmediately: true,
options: [
{
value: 1
},
{
value: 2
},
]
},
```
- src/el-data-table.md 补充特有特性说明
如果一次性为大部分表单项添加 `searchImmediately: true`:
```js
const formContent = content.map(item => {
return Object.assign(item, {
searchImmediately: true
})
})
```

feat(searchImmediately): 支持搜索表单项变更时自动搜索

---

src/el-data-table.vue

issue #234
该问题是由于树形表给 child row 增加了 `parent` 属性引用了 parent row，到时调用 `JSON.stringify` 时报 `Uncaught TypeError: Converting circular structure to JSON` 的错误。
树形表通过 `$set` 的方式给 child row 增加 `parent` 属性，`parent` 目前主要是用于控制改行的 `row-show` 和 `row-hide` 类切换（以增加过渡效果），而实际使用是通过 `el-table` 的 `row-class-name` 的函数属性值的方式，不存在响应式的绑定。
因此，可以改成通过 `Object.defineProperty` 添加 `parent` 属性，并设置 `enumerable` 属性为 `false`，因为 `JSON.stringify` 方法不会对不可枚举的变量进行转换，从而避免了循环引用的问题，又保证当前的 `parent` 在 child row 上可用。

fix: 修复树形表数据无法直接stringify的问题

---

src/el-data-table.vue

尝试了下onDelete示例，发现点击确认删除按钮没有任何反应。调试后，发现是onDelete逻辑报错，内部只是catch了没有反应。
1. 现在onDefaultDelete在catch error后会`console.warn(error.message)`然后再throw error
2. 给mock的数据加上id字段，否则onDelete示例会报错
删除逻辑正常
现在onDelete示例能正常删除了

fix: onDelete没有抛出异常的问题 

---

src/el-data-table.vue

close #244 
- 在轮询更新列表状态的场景下，getList 默认的 loading 会打断用户的操作
- 调用 getList 时可以传一个 false 来禁用 loading

feat: 刷新列表时提供一个 flag 判断是否显示 loading

---

docs/faq.md
src/el-data-table.vue

close #241 
close #238
make methods correctPage public 
抽离判断返回上一页的逻辑,方便自定义实现 delete 时,保持与 defalutDelete 行为一致
详情看 faq
- 暴露的公共方法名为 correctPage 因为讨论发现这个操作不一定是返回上一页，而是回到正确的最后一页

feat: 暴露 correctPage API

---

docs/extra-buttons.md
src/el-data-table.vue

操作栏按钮需要进行个别的禁用，并根据当前行的数据展示是否禁用的状态
类似show，给extraButton提供一个函数类型的属性disabled，函数第一个参数可以获取到该行的数据，自行处理逻辑，返回一个布尔值使得按钮是否为禁用状态，返回true为禁用，false为不禁用，默认不禁用
表格配置添加一个extraButton
extraButtons: [
{
text: '禁用',
disabled: (row)=>{
if (row.xx=='xx') return true
},
},
]

feat: extraButton添加函数类型的disabled属性

---

src/el-data-table.vue

因为 el-pagination 接收到的值，如果是 null 后者 undefined 的话，会导致 下一页可以被点击，被点击的话会触发组件的 getList。
_get 情况下，如果接口返回的是 null 的话，_get 获取不到值就会是 undefined 值
```diff
- this.total = _get(resp, this.totalPath)
+ this.total = _get(resp, this.totalPath) || 0
````

fix: 修复 el-pagination 值错误，可点击问题

---

src/el-data-table.vue

hasHeader 的判断里没有包括 `this.$slots.header`
hasHeader 存在是因为整个 header 是被包在一个 el-form 里。
el-form 存在是因为需要它的`margin-bottom: 22px`
给示例`slot-header`加上`hasNew: false`。现在 slot 能正常显示了

fix: header 部分仅有 slot-header 时，该 slot 未显示的 bug

---

docs/multi-level-header.md
src/components/el-data-table-column.js
src/el-data-table.vue

不满足当前项目需求
1. 封装一个 `el-data-table-column` 的容器组件，当传入 `columns` 时递归本身
2. 将 `el-table-column` 替换成 `el-data-table-column` 
在`columns`子项里嵌套`columns`数组
```js
columns: [
{ prop: 'date', label: '日期' },
{
prop: 'info',
label: '个人信息',
columns: [
{ prop: 'name', label: '姓名' },
{ prop: 'address', label: '地址' }
]
}
]
```
效果图
- docs/multi-level-header.md

feat: 支持多级表头

---

src/el-data-table.vue
yarn.lock

total 不为 0 的话，用户仍可翻页
1. 顺手更新了 el-form-renderer 的依赖（之前向别人用 searchForm 演示 remote 功能时，发现 styleguide 的 el-form-renderer 版本不够新
2. getList 的 catch block 里设置 total = 0
直接在 this.$axios.then 里 throw new Error()

fix: getList 出错时设置 total = 0

---

docs/custom-text.md
src/el-data-table.vue

常见需求。大量用户弃用原生 delete 使用 extraButtons 就是因此
文档 new-text 改名为 custom-text，表示这里演示自定义文案的例子

feat: 自定义删除弹窗文案

---

src/el-data-table.vue

目前业务场景中，针对后端请求的分页以及页数的参数名与组件中的不一致
目前定义成了可从外部传入 `key` 的方式去指定传到后端接口的 `key name`

feat: 添加分页自定义 key

---

docs/basic.md
src/components/el-data-table-column.js
src/el-data-table.vue

CLOSE #264 
- multi-level-header should align center but should not affect normal header
- fix issue #264
create a computed property to define if multi-level header or not
if yes, render columns with align center
if not, render columns as before
More importantly, columns property can assign the computed property
after

fix: columns property align not work

---

docs/on-default-delete.md
src/el-data-table.vue

有时候内置的删除按钮不满足产品场景；那么 table 可以公开内部完整的经过实践的删除方法，方便前端用户根据场景去调用
1. onDefaultDelete 参数传什么它删什么
2. 补充注释

docs: 公开 onDefaultDelete 方法

---

docs/is-tree.md
src/el-data-table.vue

fix #283 
原有的 showRow 方法是用来展现一个 toggle 的动画的；现在的处理是合并该逻辑与用户通过 tableAttrs 传进来的逻辑
https://deploy-preview-284--el-data-table.netlify.com/#/Demo/is-tree?q=size~999,page~1,
```js
// is-tree.md
export default {
data: function() {
return {
isTree: true,
tableAttrs: {
rowClassName({rowIndex}) {
return rowIndex === 2 ? 'is-tree-red' : ''
}
},
}
},
created() {
// FYI: styleguide 里面用不了 style block
document.querySelector('style').sheet.insertRule('.is-tree-red {color: red}')
}
}
```

fix: tableAttrs 无法修改 rowClassName 的问题

---

docs/basic.md
src/el-data-table.vue
src/utils/query.js
test/query.test.js

当查询值为数组时，经过 queryUtil 后会将整个数组变成字符串，例如：
```js
const value = [1,2,3,4]
const queryValue = value.toString().trim() // 1,2,3,4
const stringifyValue = encodeURIComponent(queryValue) // 1%2C2%2C3%2C4
const parseValue = decodeURIComponent(stringifyValue) // 1,2,3,4
```
在 encode 前先把值进行 JSON.stringify()，在 decode 后进行 JSON.parse()，同时把 JSON.stringify 放到 queryUtil 内部处理，则外部不再需要进行额外处理
```js
const value = [1,2,3,4]
const stringifyValue = encodeURIComponent(JSON.stringify(queryValue)) // %5B1%2C2%2C3%2C4%5D
const parseValue = JSON.parse(decodeURIComponent(stringifyValue)) //  [1, 2, 3, 4]
```
- 在 basic.md 添加可多选的示例

fix: 查询值为数组时的持久化问题

---

src/el-data-table.vue
src/utils/query.js
test/query.test.js

因未知原因（可能是 vue-router?）会将 地址栏 url 自动 decode，此时如果存在数组值，则会在 parse 时先被按 `,` 分割，导致无法正常解析：
```js
let url = `q=area~east%2Csouth,size~20,page~1,`
// 刷新时会被自动转换为：
url = `q=area~east,south,size~20,page~1,`
// queryUtil.parse() 方法会先按 ',' 进行分割，导致原本属于同一个字段的值丢失了，就无法正常解析了
url.split(',') // ["q=area~east", "south", "size~20", "page~1", ""]
```
encode 数组值时，先使用别的分隔符；
同时由于之前发送请求和构造地址栏的 url 用的是同一个方法，但现在由于两者 stringify 的方式不一样，所以增加一个 `URLStringify` 用于构造发送 axios 请求的参数
- 新增 URLStringify 测试用例
- 新增数组 stringify 测试用例

fix: 查询值为数组时的分隔符问题

---

src/utils/is-falsey.js
src/utils/select-strategy.js
test/is-falsey.test.js

Fix #305
searchForm 某个值为空数组时也判断为没有值
当table不存在时代理其方法不让其报错

fix: 增加searchForm 的空数组进行判断

---

docs/table-attrs.md
docs/table-props-events.md
package.json
src/el-data-table.vue
yarn.lock

fix #307 
close #308 ，区别是不用新增 prop，而且可以写 camelCase
通过 tableAttrs 支持 el-table 的 prop & eventHandler 的传递
规则是，以 on 开头的 camelCase 属性会作为事件监听器传入
新增 table-attrs.md

feat: 支持监听 el-table 事件（新增 prop：tableEventHandlers）

---

src/el-data-table.vue

当查询参数为数组时，需要将参数转化为字符串。因为在发送请求时，数组参数会被处理；列如：
``` js
const query = {
area: ['south','west']
}
//会变成
const query = {
area[]: 'south',
area[]: 'west'
}
``` 
在大多数项目中已使用数组参数，都转化为了字符串的形式。会导致查询接口报错。
只需在处理query参数时，加上一个判断，如果是使用的数组，那么将数组转化为字符串即可
``` js
const area = ['south','west']
const areaString = area.toString().trim()   // south,west
```

fix:查询参数为数组时需要将数组转为字符串形式

---

src/el-data-table.vue
src/utils/is-falsey.js
src/utils/utils.js
test/is-falsey.test.js
test/utils.test.js

fix #319 
Describe your steps:
1. 当搜索表单中搜索字段有默认值时，进入页面，搜索时传入默认值，url同步数据
2. 当搜索字段的默认值被清空时，url同步数据，并且刷新页面搜索时不会被默认值覆盖（搜索时不传入数据）
> 原来的数据为空的逻辑判断，认为空数组，空字符为isFalsey，现改为not false
- before
```js
import isFalsey from '../src/utils/is-falsey'
describe('test isFalsey', () => {
test('判断为 "",undefined或者 null', () => {
expect(isFalsey(undefined)).toBe(true)
expect(isFalsey(null)).toBe(true)
expect(isFalsey('')).toBe(true)
expect(isFalsey()).toBe(true)
expect(isFalsey(0)).toBe(false)
expect(isFalsey({})).toBe(false)
expect(isFalsey([])).toBe(true)
})
})
```
- after
```js
import {isFalsey, dealQuery} from '../src/utils/is-falsey'
describe('test isFalsey', () => {
test('判断为 "",undefined或者 null', () => {
expect(isFalsey(undefined)).toBe(true)
expect(isFalsey(null)).toBe(true) …
```

fix: 修复 searchForm 刷新后恢复默认值的问题

---

docs/axios-config.md
src/el-data-table.vue

方便对请求进行扩展
在使用组件时，默认请求方式是 get，在 axiosConfig 中添加 method: 'post' 即可修改为 post
更新 axiosConfig.md 文档

fix: 支持在 axiosConfig 中定义请求方法

---

src/el-data-table.vue

```js
{
text: "删除",
type: "danger",
atClick: async (row) => {
await this.$refs.routerTable.onDefaultDelete(row)
return false
},
}
```
配置 extraButtons 时，使用了内部的 onDefaultDelete 方法，但没有正确显示 self-loading-button 的 loading 状态
onDefaultDelete 方法返回 Promise

fix: 使用默认删除方法提供loading状态

---

src/components/text-button.vue

fix #335
1. this.style是响应式对象且已绑定到模板里面，故32-35行代码貌似做了无用功？
2. mounted时node已挂载，getComputedStyle(this.$el).color也就可以取到值，sleep 300s反而会造成取color值不对的几率

fix(text-button):  操作栏按钮的色值可能会取值不正确  #335

---

docs/slot-operation.md
src/el-data-table.vue

当 extraButtons 存在，但不完全满足需求时，需要写 template。希望原有 extraButtons 不用改写成 template
添加 slot=operation
示例代码：
展示效果：
yes

feat: slot=operation，适用于 extraButtons 不满足需求时

---

docs/on-response.md
src/el-data-table.vue

当项目中使用拦截器统一处理 repsone 时，this.$axios 返回的不一定是原始数据，此时组件的 dataPath/totalPath 失效，无法获取数据。
添加 onResponse 属性，优先使用它处理 this.$axios 返回的数据。
yes

feat(on-response): 兼容 axios 直接返回 data 的情况

---

src/el-data-table.vue

el-data-table在树形结构列表展示的是，如果显示翻页翻页页码不显示
Describe your steps:
1.  在设置翻页的情况下，设置翻页属性不起作用
You may use xmind or other mind map to show you logic
It there requires a change to the documentation？

fix: el-data-table树翻页页码不显示错误

---

src/components/self-loading-button.vue

extraButtons按钮点击去除冒泡
我生成的table加了行点击展开事件，但是extraButtons中的操作按钮点击同样会触发行点击展开，extraButtons中的操作按钮应该仅做它相应的操作事件

fix: extraButtons按钮点击去除冒泡
